@echo off
echo Starting Widgetic Application...
start "Widgetic Server" cmd /k "cd server && npm run dev"
start "Widgetic Client" cmd /k "cd client && npm run dev"
echo Services starting in separate windows...
